Repository studata-platform/studata-api, pull requests merged in 2019-11, with the labels that each got.

#2 Feature/graphql setup
  README.md
  package-lock.json
  package.json
  scripts/start.ts
  scripts/util/watchMain.ts
  src/graphQlMiddleware.ts
  src/graphQlSchema.ts
  src/graphql/context.ts
  src/graphql/index.ts
  src/graphql/middleware.ts
  src/graphql/page/index.ts
  src/graphql/page/resolvers/index.ts
  src/graphql/page/resolvers/page.ts
  src/graphql/page/schema.ts
  src/graphql/quickScan/index.ts
  src/graphql/quickScan/resolvers/index.ts
  src/graphql/quickScan/resolvers/quickScan.ts
  src/graphql/quickScan/resolvers/saveQuickScan.ts
  src/graphql/quickScan/schema.ts
  src/graphql/schema.ts
  src/index.ts
  src/server.ts
Labels: enhancement

#3 Update c6-partners title
  src/graphql/page/resolvers/page.ts
Labels: bug

#4 Add target group value to hero buttons
  src/graphql/page/resolvers/page.ts
Labels: enhancement

#5 Feature/quick scan question resource
  src/config.ts
  src/data/Target.ts
  src/database/createMongooseConnection.ts
  src/database/createMongooseModel.ts
  src/database/model/QuickScan/index.ts
  src/database/model/QuickScan/quickScanSchema.ts
  src/database/model/QuickScanQuestion/index.ts
  src/database/model/QuickScanQuestion/quickScanQuestionSchema.ts
  src/database/model/QuickScanResult/index.ts
  src/database/model/QuickScanResult/quickScanResultSchema.ts
  src/database/model/index.ts
  src/graphql/index.ts
  src/graphql/quickScan/index.ts
  src/graphql/quickScan/resolvers/index.ts
  src/graphql/quickScan/resolvers/quickScan.ts
  src/graphql/quickScan/resolvers/saveQuickScan.ts
  src/graphql/quickScan/schema.ts
  src/graphql/quickScanQuestion/index.ts
  src/graphql/quickScanQuestion/resolvers/createQuickScanQuestion.ts
  src/graphql/quickScanQuestion/resolvers/deleteQuickScanQuestion.ts
  src/graphql/quickScanQuestion/resolvers/index.ts
  src/graphql/quickScanQuestion/resolvers/quickScanQuestions.ts
  src/graphql/quickScanQuestion/resolvers/updateQuickScanQuestion.ts
  src/graphql/quickScanQuestion/schema.ts
  src/graphql/schema.ts
  src/server.ts
  src/types/IQuickScanQuestion.ts
  src/types/MongooseModels.ts
Labels: enhancement

#6 Add salutation field to quickScanQuestion
  src/database/model/QuickScanQuestion/quickScanQuestionSchema.ts
  src/graphql/quickScanQuestion/schema.ts
Labels: enhancement

#7 Feature/quickscan result resource api
  src/database/model/QuickScanResult/quickScanResultSchema.ts
  src/graphql/index.ts
  src/graphql/quickScanResult/index.ts
  src/graphql/quickScanResult/resolvers/createQuickScanResult.ts
  src/graphql/quickScanResult/resolvers/deleteQuickScanResult.ts
  src/graphql/quickScanResult/resolvers/index.ts
  src/graphql/quickScanResult/resolvers/quickScanResult.ts
  src/graphql/quickScanResult/schema.ts
  src/graphql/schema.ts
  src/types/IQuickScanQuestionResult.ts
Labels: documentation, enhancement

#9 Update File Name Quickscan api
  src/types/IQuickScanResult.ts
Labels: enhancement
